### ISSUE TITLE
Advanced Coke Oven (Modern Industrialization) does not form

### ISSUE THREAD

**Issue by arisgoun** [FTBTeam/FTB-Modpack-Issues#10121]
### Modpack

FTB Skies 2

### Modpack version

1.9.2

### Launcher

CurseForge

### Describe the bug

As in the title.

Note that the material list says 12 bricks and 12 coke bricks (total 24).
Excluding the hatches (3, one item input, 1 item output and one fluid output) there are materials left out. (only 12 bricks used) I tried to add another level (another 8, to make it 20) but still it does not form.

There is no information about the multiblock in the guide. I followed JEI to make it.

### Steps to reproduce

1. Set up the Advanced Coke Oven using the wrench to see where the block go
2. Upon completion, it stays at "Shape Invalid"

### Expected behaviour

The multiblock to form

### Has the pack been modified

No

**Comment by leapbtw** [comment]
mine works, you need an energy hatch

**Comment by arisgoun** [comment]
Not for me ...
I tried with MV and LV energy input hatch.

I followed the schematic that appears having placed down the controller and holding the wrench.

My build is as follows:
Bottom level:
- Front: Item input hatch, controller, item output hatch
- Middle: Brick, spirit fire, fluid output hatch
- Back: Energy hatch, brick, coke brick
Upper level:
- Front: Coke brick, brick, coke brick
- Middle: Brick, iron bar, brick
- Back: Coke brick, brick, coke brick

What am I doing wrong?

**Comment by arisgoun** [comment]
Issue remains in 1.12.

Any ideas?

**Comment by LegendaryRylex** [comment]
I think I know what the problem is. The controller block goes in the "middle layer", so from your build only having 2 layers I'm assuming you're missing one :P

**Comment by arisgoun** [comment]
Thanks, you are correct. I fixed it.

Unfortunately, there is no image of the multiblock in the guide. And, if you place the controller on a flat surface (as I did), the bottom layer of the multiblock shadow (when holding the wrench) is clipped. So, the structure looks like two blocks tall, as I described ...

**Comment by Guardian2043** [comment]
I built the advance coke oven but it still won’t work I got a lv energy hatch item input and out put for item and fluid it says shape valid but still nothing
