### ISSUE TITLE
[Bug]:  FTB OceanBlock lets wife play, now she can't join existing game. Can join fresh game though.

### ISSUE THREAD

**Issue by Recca1982** [FTBTeam/FTB-Modpack-Issues#106]
### Modpack

FTB Oceanblock

### Modpack version

1.2.0

### Log Files

[crash-2021-10-08_18.26.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7314523/crash-2021-10-08_18.26.39-client.txt)

### Describe the bug

My wife and I play on a LAN server.  Sometime today, I became unable to remove myself from creative via /gamemode survival.  so in order to attempt at "fixing" it.  I restarted my game (which is the host client).  Loading back in, the issue persists, but I found I can use the button in the top left to change gamemodes, and it WORKED.  During that time, my wife went to rejoin the world and spawned not where she logged out, but in the ground on the other side of the island and died.  When she died, she got removed from the server and could no longer join with a varying amount of issues (her log is attached).

Not sure what's causing it to be honest.

### Steps to reproduce

1) make a server
2) play on the server for roughly 24-48 hours without logging off (leaving server running for mob farm efficiency)
3) have no idea what's going on and can't change back from creative
4) restart server
5) fail,... or success? Hmm

### Expected behaviour

Expected gamemode to be able to be changed via command, and wife to be able to connect to the game.

**Comment by Raidobw2** [comment]
Hi Recca1982!
There is currently a bug from the MineTogether mod that has been fixed in dev for the mod, but not released yet. The details are found at: #67.

When a client disconnects wrongly from a server -- in your case you play in LAN, they will crash with that message. I've observed players having this fixed temporarily by installing the RandomPatches mod on both servers and clients.

This mod makes the login read timeout 3 times higher than normal (90 seconds total) and helps joining the game at times, instead of having a disconnection occur. It is obtainable at https://www.curseforge.com/minecraft/mc-mods/randompatches-forge, but you can also directly install it in the FTB App under the Mods section, in the modpack page.
A reminder that both ends need the mod for it to work, in that case you and your wife.

Let me know if that works as a temporary solution so i can close this ticket since it is a duplicate!

Otherwise i will have you remove the mod and do a special config to allow you both to resume playing if RandomPatches didn't work,

R3GEN

**Comment by Recca1982** [comment]
Hey, sorry it took so long to get back to ya.  Work and all.

Anyways, just tried RandomPatches mod.  While that fixed the /gamemode survival issue, she still cannot connect :/

**Comment by Raidobw2** [comment]
Hello,

I'll write a quick procedure to remove the Minetogether mod.
In the FTB App on the modpack page you can click Settings at the right. Then you should be able to click Open Folder at the bottom. We'll call the opened view "the modpack folder".

First, you need to delete the minetogether jar file in the `mods` folder, probably called `minetogether-1.16.5-5.0.0Alpha6-forge.jar`.

Second you'll need to adjust the script for the menu screen. In the modpack folder, navigate through the path: `kubejs/client_scripts` and open `main_menu.js` with a text editor. There is a whole block of code for the mod to remove in order for the game to load properly. A day or two ago i had written a corrected file at <https://paste.feed-the-beast.com/view/ea91dc5d>, where you will see the comment in the file "_//Here lies the old Minetogether block of code that is now removed_" replacing part of the old code. You can simply copy the whole contents of that paste and replace the whole contents of the script. Once the changes are done, make sure to save the file.

Afterwards boot up whichever game had the crash you posted in your original message, and they shouldn't get crashes anymore.

Please let me know later if that fixed it for either game that was crashing.

**Comment by Recca1982** [comment]
Weirdly enough, neither computer has a Main_menu.js in that folder o.
![mainmenu](https://user-images.githubusercontent.com/92188390/136713261-1197b4ed-8bb9-4e9f-9127-a68c75ab7d2e.jpg)
O

**Comment by Raidobw2** [comment]
Woops, i might have been mistaken. Sorry i had another user with the same issue on a different modpack, it gets confusing at times!

You should be able to just remove the mod, there is no script no adjust in OceanBlock, my mistake.

Let me know how it goes!

**Comment by Sunekaer** [comment]
Packupdate released

**Comment by Recca1982** [comment]
Well, just letting you know the pack update didn't fix this issue, however Raidobw2's solution of just deleting minetogether worked beautifully.

Thanks Raido!
