### ISSUE TITLE
World so not open after 100% loading

### ISSUE THREAD

**Issue by ChristianZeolla** [FTBTeam/FTB-Modpack-Issues#10755]
### Modpack

FTB StoneBlock 4

### Modpack version

1.2.1

### Launcher

FTB App

### Describe the bug

My "new world" do not oper after reaching 100% loading world. Don't crash and you can only alt-F4 for killing this instance

### Steps to reproduce

Oper FTB APP
Launch stoneblock 4
Singleplayer
Open world
Loading at 100%
Don't go after this and open the world
Stay in the loading world screen without crashing

### Expected behaviour

Open world correctly

### Has the pack been modified

No

### Additional information

[debug.log](https://github.com/user-attachments/files/23936673/debug.log)

**Comment by Nightcaste** [comment]
I am having the same problem on an existing world that was originally created on version 1.0.3, then updated through multiple versions up to 1.2.1.

I was able to get it to open by restoring from a backup, but that has not worked a second time.

The most recent failure gave a "Network Protocol Error" message even though I was on single player.

**Comment by ChristianZeolla** [comment]
There is no debug code because the modpack do not crash, but remain in thr loading state

> These are watchdog issues. This means that something in the world is taking too long to load, usually due to a farm overflowing with entities. Please provide the debug log as well.

**Comment by Nightcaste** [comment]
[debug](https://mclo.gs/rlEQ9Dt)

[Latest](https://mclo.gs/Ne6XMCL)

**Comment by Nyxane** [comment]
This will be fixed on latest as it relates to the Diaphanous Block Recipe issue causing it to not load

**Comment by Dominator016** [comment]
Wait im confused so this issue is going to be fixed with the next update?

**Comment by Spiker985** [comment]
After some testing, much like @Nyxane reported, the issue is an incompatibility between Refined Storage and Irregular Implements which has been fixed [here](https://github.com/Berry-Club/Irregular-Implements/issues/56) but which does not yet have a newly released version. Hence the "Fixed in Dev" tag.

If you're being blocked at loading the world, disabling Advanced Loot Info should allow you to load into the world - but you will appear to be falling into the void. This is to be expected, but is a positive confirmation that you're encountering the issue.

If anyone is encountering this issue, you can likely downgrade to 1.1.2 to continue playing for the time being **[THIS MAY RESULT IN LOST DATA, MAKE COPIES AND PERFORM AT YOUR OWN RISK]**

**Comment by Nightcaste** [comment]
I'm not finding a .js file for "random things" or "irregular implements" in the kubejs folder

**Comment by nightstick24** [comment]
> To anyone encountering this issue, you can remove the diaphanous block recipe if you know your way around KubeJS, otherwise please be patient with an upcoming update that will remove the diaphanous block recipe to fix this world loading problem

I don't think this fixes it - the Changelog for 1.3.0, which is public, mentions "Removed recipe for Disphonous block" and this issue persists.

**Comment by Nightcaste** [comment]
> Looks like recipe removal introduces a race condition, which isn't ideal, the only solution is to wait for irregular implements to update. Which we are closely monitoring.

I figured it it would be something like that,  I just posted here in case someone else had this issue,  sees this,  and then they know 1.4.0 isn't the fix

**Comment by ApparentlyACat** [comment]
The fix is updating Irregular Implements to 1.8.1 then the modpack works on 1.4.0.

**Comment by HornsGuy** [comment]
> The fix is updating Irregular Implements to 1.8.1 then the modpack works on 1.4.0.

This worked for me. Thanks everyone who contributed to finding a workaround. I was going crazy trying to troubleshoot this on my own.

**Comment by CodeClumsy** [comment]
> The fix is updating Irregular Implements to 1.8.1 then the modpack works on 1.4.0.

This worked for me as well, glad I found this. Thanks much
