### ISSUE TITLE
[Bug]: [Integrated Dynamics] Machine recipes don't show up in JEI

### ISSUE THREAD

**Issue by v-tron** [FTBTeam/FTB-Modpack-Issues#1257]
### Modpack

Direwolf20 1.18

### Modpack version

1.9.0

### Describe the bug

Right clicking the Mechanical Squeezer or the Drying Basin or Liquid Menril/Chorus in the JEI yields no recipes. Recipe button in Mechanical Squeezer UI doesn't work.

### Steps to reproduce

1. Go to JEI
2. Click Liquid Menril/Chorus

### Expected behaviour

Recipes should show up in JEI

**Comment by PutNameHere42** [comment]
This has been addressed multiple times and this issue will probably be closed since its a duplicate. Roll back your version of JEI to the last full release, it'll solve the recipe issues.

**Comment by Raidobw2** [comment]
Hotfix 1.9.1 has been released make sure to update, this should be solved!

**Comment by faanlez** [comment]
The JEI downgrade doesn't seem to fix this one, the recipe categories are completely missing.

**Comment by v-tron** [comment]
Yep, not fixed unfortunately.

**Comment by TheonlyTazz** [comment]
i have confirmed that this is actually caused by the latest update of Integrated Dynamics (IntegratedDynamics-1.18.2-1.11.8.jar)

https://github.com/CyclopsMC/IntegratedDynamics/issues/1203#issuecomment-1214430486
Quote from Rubenswork:
> ID 1.11.8 requires JEI of version 10.x, so updating JEI will fix your problem. If you can't update JEI, please downgrade ID to the previous version.

so untill JEI10 is compat with all other stuff like Thermal and such, we need to downgrade Integrated Dynamics to 1.11.7

I will do this in the Dev-enviroment and this will be shipped in the next update
