### ISSUE TITLE
[Bug]: Game crashes when searching within REI

### ISSUE THREAD

**Issue by RealDDA** [FTBTeam/FTB-Modpack-Issues#1601]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Log Files

[crash-2022-11-03_22.39.28-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9930359/crash-2022-11-03_22.39.28-client.txt)
[crash-2022-11-03_22.48.02-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9930360/crash-2022-11-03_22.48.02-client.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9930364/latest.log)

### Describe the bug

Game crashes every time you search for anything within REI.

### Steps to reproduce

1.Set the game language to Simplified Chinese
2.open inventory tab
3.Type any text into REI's search box
4.game will crash

### Expected behaviour

I hope this will be fixed soon.

**Comment by RealDDA** [comment]
1.0.2,crash still exists.

**Comment by RealDDA** [comment]
1.0.2,crash still exists.

**Comment by Sunekaer** [comment]
Could you try and remove emojiful from the mods folder and see if it still happens?

**Comment by RealDDA** [comment]
> 您能否尝试从 mods 文件夹中删除 emojiful 并查看它是否仍然发生？

I removed emojiful and the crash didn't happen anymore.  thank you!

**Comment by RealDDA** [comment]
> Could you try and remove emojiful from the mods folder and see if it still happens?

I deleted emojiful and the crash still exists.
[crash-2022-11-05_14.21.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9943206/crash-2022-11-05_14.21.01-client.txt)

**Comment by Raidobw2** [comment]
When you have a chance, after the Emojiful mod is removed, can you add your latest.log here? It's the one that contains the errors this time

**Comment by RealDDA** [comment]
> When you have a chance, after the Emojiful mod is removed, can you add your latest.log here? It's the one that contains the errors this time

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946371/latest.log)
sure!

**Comment by Raidobw2** [comment]
I've forwarded it to the mod author just above, thanks!

If you want to resume playing without crashes, you can try downgrading the REI version to this one:
![image](https://user-images.githubusercontent.com/17010632/200297912-79b942d4-b031-4278-b4c8-12d58fc53e63.png)

You need to downgrade both the REI and REI Compatibility Layer, these ones should work:
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/4040775
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks/files/4036397

These versions will cause the "+" to not work in the AE2 Crafting Terminal, but at least that should enable you to continue playing until REI can update again.

Let me know if it worked if you try it!

**Comment by Sunekaer** [comment]
Please test if fixed in 1.1.1

**Comment by RealDDA** [comment]
> Please test if fixed in 1.1.1

1.1.1,the crash still exists.
[2022-11-08-3.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9963221/2022-11-08-3.log)

[crash-2022-11-08_20.13.05-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9963219/crash-2022-11-08_20.13.05-client.txt)

**Comment by Sunekaer** [comment]
Thanks, i opened an issue with the dev of the mod https://github.com/shedaniel/RoughlyEnoughItems/issues/1202

**Comment by RealDDA** [comment]
> 谢谢，我向 mod [shedaniel/RoughlyEnoughItems#1202的开发人员提出了一个问题](https://github.com/shedaniel/RoughlyEnoughItems/issues/1202)
After updating to 1.2.0, the crash doesn't seem to appear anymore.Thanks!
