### ISSUE TITLE
Client can't join a LAN server

### ISSUE THREAD

**Issue by Trelsonowsky** [FTBTeam/FTB-Modpack-Issues#2283]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Log Files

https://pastebin.com/SVxW483R

### Describe the bug

My friend can't join LAN server. She gets error "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException"

### Steps to reproduce

1. One kit hosts a LAN server from pause menu.
2. Second kit joins the server
3. Observe the issue

### Expected behaviour

Second kit is able to join server

**Comment by manmaed** [comment]
can you confirm if this is still an issue in 1.0.4?

**Comment by Trelsonowsky** [comment]
EXactly the same on 1.0.4, I remember we had the same issue with error 37 on some other FTB modpack on 1.18 but ATM7 works with no issues.

**Comment by Saereth** [comment]
I need the latest.log or debug.log from both of you if possible to see what the issue is

**Comment by Trelsonowsky** [comment]
[client_debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10200465/client_debug.log)
[client_latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10200466/client_latest.log)
[host_debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10200467/host_debug.log)
[host_latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10200468/host_latest.log)

**Comment by HumanForerunner** [comment]
Same issue. Can't upload logs atm.

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2312

**Comment by Trelsonowsky** [comment]
Any new info? Is this being worked on? At least 8 people can't play because of this

**Comment by NeosGhost** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2412#

**Comment by Jamesyt666** [comment]
Just tried to play this with my son and ended up here... :-(

**Comment by Trelsonowsky** [comment]
I can't really test it now, but you could try and copy mods to a new instance in different launcher such as MultiMC with the same version of java and forge. I mean only mods and none of configs and datapacks

**Comment by Jamesyt666** [comment]
what you suggest is a good thing to try. I can't test right now as its Minecraft time with my 7-year-old but I can try that later on and feed-back.

**Comment by NeosGhost** [comment]
with the same forge version and mods but no configs or datapacks copied I get the same thing. Used multiMC and GDLauncher

https://i.imgur.com/T5rVwbm.png

**Comment by ReignerNoe** [comment]
Same problem as described. I can´t join mi local LAN game in Direwolf 20 1.19, other modpacks works withaout issue.

**Comment by Trelsonowsky** [comment]
@ReignerNoe other FTB modpacks? What mc versions are they on?

**Comment by HPeti** [comment]
I have the same issue with "Open to LAN" and "Open to friends" (this feature is in minetogether). I've used version 1.0.4.

A temporary workaround would be that you can set up a "dedicated server" on your computer, but RAM usage is a problem, so a fix would be nice on the client.

Links:
- https://feed-the-beast.com/modpacks/server-files
- https://feedthebeast.notion.site/Installing-a-Feed-the-Beast-Server-aeaea8a7220945d0ad0357c80c6c9d12

**Comment by Trelsonowsky** [comment]
I'll try using it but RAM won't be the issue. I'd say CPU usage will be the real problem since mincecraft can realistically use one core. Will server be able to use second (or even more) core?

**Comment by Trelsonowsky** [comment]
Can confirm that local server using provided server files is working. Im getting constant 100+ frames with 6GB assigned to server and to my client. TPS is stable 20ms but theres a noticable lag when backup starts. As a temporary fix it's playable.
i7-10700F

**Comment by Saereth** [comment]
This should be resolved now in 1.4.0, I tested it on lan locally in my houshold with 2 other pcs, if you encounter the issue again please open a new issue with your updated version.

**Comment by Trelsonowsky** [comment]
But there's no 1.4.0 version??

**Comment by Trelsonowsky** [comment]
@Saereth you mean 1.0.4? I already said that the issue persists on newer versions

**Comment by NeosGhost** [comment]
> This should be resolved now in 1.4.0, I tested it on lan locally in my houshold with 2 other pcs, if you encounter the issue again please open a new issue with your updated version.

tested on version 1.1.1 nd problem still persists

**Comment by NeosGhost** [comment]
updating moonlight lib mod version fixed the issue. recommend version 2.2.0.

**Comment by Syreyne** [comment]
My husband and I are on version 1.19.  Yesterday, everything with LAN worked fine.  Today, nothing works with LAN or Play With Friends.  For LAN, it keeps saying the connection timed out, different from the previous errors we were getting.  We both updated to the same version, done the typical restart of PCs, and everything else.

It really sucks that we created a world together and now I can't play on it, nor have I found a solution to this issue.
