### ISSUE TITLE
DW20 1.19 ver 1.5.0 Failed to get registry access.

### ISSUE THREAD

**Issue by Hobbziie** [FTBTeam/FTB-Modpack-Issues#2768]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.5.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10858767/latest.log)

### Describe the bug

Every time you try connect to server you will receive the error "Internal Exception: java.lang.UnsupportedOperationException: Failed to get the registry access. This is a bug"

### Steps to reproduce

Happens every time you try connect to my server after it stats joining world.

### Expected behaviour

To log into the server

### Screenshots

![image](https://user-images.githubusercontent.com/126657913/222088329-962294f7-7881-4bbe-bfe2-ecaac4c6a724.png)

![image](https://user-images.githubusercontent.com/126657913/222088481-0b2a4c71-08a7-4fc8-891b-7bb321c1e4b5.png)

### Additional information

I have already tried following the advice of disabling the connectivity mod on the server and restarted the server but the error still appears.

If I uploaded wrong log I apologise just let me know and I will find the correct one.

**Comment by freakyfreaky** [comment]
Having the same error, even I upload the xnet file manually or updating twice

**Comment by JakeMoe** [comment]
Same issue; I've updated client and server to 1.5.0 and now can't join, getting the same error as well.  Client is running via FTB App on Arch, server is a local Ubuntu.

**Comment by Spaceferret42** [comment]
Having the same issue had to downgrade to version 1.4.0

**Comment by hardytm426** [comment]
> The issue apparently comes from Moonlight Lib or/and Supplementaries. I think best solution is just to go back to 1.4.0 and wait for 1.6.0 to come out and hope this has been fixed in it.
> 
> But if anyone wants to mess about instead of waiting.. Replace current Moonlight Lib & Supplementaries with these: Moonlight Lib 2.2.9 Supplementaries 2.2.50
> 
> You need to replace both as newer versions of Supplementaries require newer version of Moonlight Lib. No guarantees for this being proper solution to the issue or that it won't bring other issues, but atleast I got my game and server to work with this.

I can confirm that rolling these two mods back to the versions specified by Yukkun does allow you to log back into the server.  I've not played on it at all since, but I did verify that my time in a bottle was properly replaced with the temporal pouch.

**Comment by PentoreXannaci** [comment]
the same issue happens to the newest FTB One version!

**Comment by westingham** [comment]
I am experiencing this issue as well.

**Comment by shank3001** [comment]
> Moonlight Lib 2.2.9 S

Works for me as well. Thanks!!!

**Comment by natebc** [comment]
I notice that 1.5.0 had gone from Beta to Release. Did this issue get fixed in the released version?

**Comment by are-mack** [comment]
I am still getting this error this morning. I just rolled back to 1.4.

**Comment by Hobbziie** [comment]
> The issue apparently comes from Moonlight Lib or/and Supplementaries. I think best solution is just to go back to 1.4.0 and wait for 1.6.0 to come out and hope this has been fixed in it.
> 
> But if anyone wants to mess about instead of waiting.. Replace current Moonlight Lib & Supplementaries with these: Moonlight Lib 2.2.9 Supplementaries 2.2.50
> 
> You need to replace both as newer versions of Supplementaries require newer version of Moonlight Lib. No guarantees for this being proper solution to the issue or that it won't bring other issues, but atleast I got my game and server to work with this.

I would advice anyone getting this issue to try this method seems to be the only fix even if a temp one to the problem, otherwise I would say it's best to wait on ver 1.6.0 as I'm sure the FTB team will have got it worked out by then.
(Thank you Yukkun for the solution <3 )

**Comment by natebc** [comment]
Might want to leave this open so that the folks making the modpack have a chance to see it if they haven't already.

**Comment by phit** [comment]
how does a version like this get marked as release? is there 0 testing done if it at least works as a server?

**Comment by PentoreXannaci** [comment]
> how does a version like this get marked as release? is there 0 testing done if it at least works as a server?

i was asking myself the same thing.
its the same with FTB One.  the 2.0 just got released few days ago with the same issue.
this seems too rushed.
(i mean they released an extra server pack, so that means the server is not even tested if its working?)

**Comment by dalgrim** [comment]
I had this issue as well. Had to manually roll server back to pack version 1.4.0 to resolve. Manually downgrading Supplementaries to 2.2.50 and Moonlight Lib to 2.2.9 did NOT fix the issue.

**Comment by dsf3449** [comment]
Just tossing in that this issue is also happening on FTB One, and that downgrading Moonlight & Supplementaries to the suggested versions above on both the server & clients resolves the issue.

**Comment by Saereth** [comment]
got an update coming today to address this

> how does a version like this get marked as release? is there 0 testing done if it at least works as a server?

Because this was tested on our internal server and we did not experience this issue.

**Comment by phit** [comment]
Ok, that's odd, but fair. Now I'm still wondering, why was 1.5.0 marked as a release instead of beta with this issue being opened 4 days prior? I get it, as server owners we should test updates too, but I had kinda gotten used to when FTB marks it as release, usually 24 hours or so after the update came out, it's safe to update.

**Comment by Saereth** [comment]
Perfectly valid questions, I'll try to give some detail. It is normal practice that for us that we'd revert to or completely archive a broken release however our stats were showing that majority of the userbase was not having this issue (we track the connection failure statistics with people who opt in with auxilium) so we didnt see it as a big enough threat to yank it (which means those servers thast were working and deployed could no longer get the pack version to their players) and instead decided to focus on getting a fix out asap which I'll have out today.

**Comment by Jwh1o1** [comment]
@Saereth Just to make sure is this a client bug or will we need to update the server as well?

**Comment by VansTheMan** [comment]
Experiencing the issue from the OP with fresh install today attempting to connect to my dedicated server which was also a fresh install today. I'm also going to try downgrading to 1.4.0

**Comment by JakeMoe** [comment]
@VansTheMan If this is a fresh install of 1.5.0, you should upgrade to 1.6.1.

**Comment by VansTheMan** [comment]
Everything seems to be working fine with 1.4.0, so I think I will stick with that for now since the launcher even says that 1.6.1 is an unstable build and to expect bugs. I just want to play games with friends, not troubleshoot a modpack. :D Thank you!
