### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vashidu** [FTBTeam/FTB-Modpack-Issues#411]
### Modpack

FTB Endeavour

### Modpack version

1.7.0

### Describe the bug

Oh the biomes you'll go wood is unable to make chests

### Steps to reproduce

1. goto a BYP biome
2. get wood
3. make planks
4. make crafting table
5. try to make a chest

### Expected behaviour

make a chest

### Screenshots

![image](https://user-images.githubusercontent.com/960246/144507471-ba9af4bb-49dc-4841-a829-fa8790a51d67.png)

**Comment by Vashidu** [comment]
looks like this was fixed in https://github.com/VazkiiMods/Quark/issues/2897

**Comment by Raidobw2** [comment]
Interesting, thanks for the report and the research you have done as well.

**Comment by Raidobw2** [comment]
I updated Quark but that didn't fix it :/ I've added recipes for all BYG wood types for you to make chests. Barrels already used the right tag so it sounds like the chests were the only problem. Every other Quark chest is untouched, this only added recipes.
![image](https://user-images.githubusercontent.com/17010632/148384717-345cf9ce-e91c-4a73-ad4d-51c988b8199a.png)

**Comment by Raidobw2** [comment]
Should be fixed in 1.9.0
