### ISSUE TITLE
FTB Genesis - Slowness effect acquired from carrying a second backpack in inventory doesn't disappear

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-Modpack-Issues#4202]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

I crafted a second backpack, only to find out carrying it is giving me slowness (good job to neutralize my pack mule habit, devs). However even after you leave the backpack away and the effect has a chance to tick down to 0:00, it doesn't disappear, until you relogin. 

### Steps to reproduce

1. Get two backpacks
2. Observe slowness is renewed as effect
3. Leave one backpack away
4. Wait 3 seconds. 

### Expected behaviour

Effect disappears after it ticks down to 0:00

**Comment by Saereth** [comment]
new sophisticated backpack update should solve this in the next release

**Comment by KaiAndreas1** [comment]
I am on version 1.4.0 and i still see this issue, I have to use a terrawart to get rid of the slowness effect after leaving the 2nd backpack
