### ISSUE TITLE
Diesel generator doesn´t spin connected shafts after joining on world

### ISSUE THREAD

**Issue by Schlauchiboy** [FTBTeam/FTB-Modpack-Issues#5035]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

Since 1.6.0 the diesel generator doesn´t spin connected shafts when joining the world. After replacing the shaft connected to it it starts spinning. Had no problems on previous versions. I think this only happens with the normal diesel generator. It has fuel and is showing that it´s working but doen´t spin anything. As is said it happens everytime i join on my world.

### Steps to reproduce

1. Have a working diesel generator with machines connected to it
2. Rejoin
3. Machines and shafts are not spinning

### Expected behaviour

Generator should not stop spinning after rejoin.

**Comment by kmadstarh** [comment]
Are the shaft and the diesel generator in different chunks/regions?

**Comment by LeanderBockholt** [comment]
Thus Issue Happens to me Not after joining but after I restart the Server and it does Not only affect the normal diesel Generator but also at least the advanced one

**Comment by Schlauchiboy** [comment]
> Are the shaft and the diesel generator in different chunks/regions?

No they are in the same chunk. Happens to all of my diesel generators

**Comment by Schlauchiboy** [comment]
> This Issue Happens to me Not after joining but after every restart of the Server and it does Not only affect the normal diesel Generator but also at least the advanced one

Same for me. I play on a singleplayer world so every rejoin means restart of the world

**Comment by Saereth** [comment]
this should be resolved with 1.8 update which includes a fix from custom machines

**Comment by ankeris** [comment]
Still happens in 1.8.1, need to either change the values of speed controllers to activate. Some diesel generators are emptied of fuel also after server restart.
