### ISSUE TITLE
Forge hammer not accepting hammers

### ISSUE THREAD

**Issue by slay-mithos** [FTBTeam/FTB-Modpack-Issues#5362]
### Modpack

FTB NeoTech

### Modpack version

1.2.0

### Pack has been modified

- [ ] Yes

### Log Files

https://pste.ch/nupemidami.md

### Describe the bug

Since updating from 1.1.0 to 1.2.0, the forge hammer no longer accepts hammers (from "just hammers").
The recipe viewer EMI also no longer shows the hammers in the recipes as it did in the previous version.

This effectively halts any progress in the early game as it is a necessary step to get from ores to dusts that can be smelted.

It apparently doesn't affect everyone so I tried to restart the game and to repair the pack, neither worked.

### Steps to reproduce

Open the GUI of a Forge Hammer
Try to place a hammer in the hammer slot
If it doesn't go in, that's it.

Alternatively, lookup the uses of a Forge Hammer in EMI to see the recipes using it.
If the hammer slots is empty in all recipe despite showing a durability cost for some recipes then you reproduced it.

### Expected behaviour

The hammer should go into the hammer slot as it is part of the recipe

### Additional information

I have noticed errors in the log that look like this:
[21Jun2024 23:09:08.408] [Render thread/WARN] [thelm.jaopca.data.DataInjector/]: Recipe with ID jaopca:immersiveengineering.raw_material_to_dust_hammer.antimony errored
java.util.NoSuchElementException: No value present

This should be related but I don't understand why it seems to be working for others.

**Comment by Saereth** [comment]
can you post your kubejs/server_scripts/tags.js file please as well as your full latest.log

**Comment by slay-mithos** [comment]
The log I pasted was latest.log, so here is the tags.js:
https://pste.ch/tihuwoyuco.cs

**Comment by slay-mithos** [comment]
I had some time so I decided to update to 1.2.1 and now it works properly again.
I have no idea why it happened but it seems fine now.
Should I close it?

**Comment by Saereth** [comment]
yeah if its working now it sounds like a file didnt properly download, there was an issue with our installer that is now resolved so I suspect that was what happened

**Comment by EQLucky** [comment]
@Saereth I don't know if this is the way (reopening a closed issue), but I am facing the same problem as @slay-mithos:
- I can't place the hammer in the Forge Hammer.
- The hammer slot is empty in EMI.
- I am in version 1.3.0, but it already happened in 1.2.0 and 1.2.1-
- I started two new games, one in creative, another one in survival. Same issues.

I have two screenshots, and I can provide any logs needed. 
If this isn't the way, I will open a new issue.

Thanks!

**Comment by Griese009** [comment]
Sorry to bother you but it seems still happening for some of the people

I updated today from 1.2.1 to 1.3.0 
as you can may see in the latest.log file i uploaded the recipes for the hammers are erroring.

I fixed it with a /reload while beeing in the world
[Uploading latest.log…]()

**Comment by Jobjeuh** [comment]
Same is happening to me. I am on 1.3.0 and I can't place a hammer (any hammer) in the left most slot of the Forge Hammer. It will only go in the second slot from the left

**Comment by joey-ops** [comment]
i still have this problem even after i tried al the things you guys said and im on 1.3.o as well any suggestions?

**Comment by slay-mithos** [comment]
Running the "/reload" commandshould fix it like jobjeuh said above you.
It seems to be one of the cubejs issues, similar to the one where your empty hand acts like a wrench.

Sometimes even the /reload command doesn't exist so you have to close the game and start it up again if that happens.

CubeJS seems to not be entirely stable in this pack sadly.

**Comment by MUMMALAMA** [comment]
I'm brand new to a lot of these packs and this is also not working for me.  I have tried "/reload" and I have completely relogged the game and this still does not work.  Just adding this to get a notification.

**Comment by preeeb** [comment]
I am typing /reload and it is saying it is an unknown or incomplete command. I am using the neotech modpack for reference. Anyone know another way I can reload?

**Comment by Griese009** [comment]
to be able to execute /reload you are required to be able to cheat - need op rigths on the world
the other working alternative was to restart the client & server (depending on what you play)

**Comment by zigzags71** [comment]
Still having the same issue in 1.7.0 . /reload works

**Comment by robotnikthingy** [comment]
Also having the same issue with Neotech 1.8.1

**Comment by pixelmixer123-hue** [comment]
1.11.1 and still dont work. Not even with /reload
developers, just wtf...
