### ISSUE TITLE
Time for FREEDOM! not awarding.

### ISSUE THREAD

**Issue by NaterTheTater** [FTBTeam/FTB-Modpack-Issues#5496]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

I have made the 6 steel pipe machine casing's but it will not complete and distribute rewards.

### Steps to reproduce

Make all the required items for the Oil drilling rig and it will not reward.

### Expected behaviour

It should reward the rest of the required materials to build the oil rig.

### Screenshots

![FTB_NeoTech_02](https://github.com/user-attachments/assets/339f13aa-f25c-4b4f-9f73-9caaff5584a1)
![FTB_NeoTech_01](https://github.com/user-attachments/assets/9620d3b0-ad18-4df2-a490-ee30ba047463)

**Comment by CattGoddess** [comment]
I am having this same issue, I have even build the whole rig. When you mouse over the quest line it says 100% in grey.

**Comment by Saereth** [comment]
this should be fixed in 1.5.0 but you might need to reset the progress on that quest

**Comment by oronm18** [comment]
Hey! I am using 1.6.0 but still having that issue, can u help me solve it? (I am on a server so I can not reset my quests)

**Comment by MaffooClock** [comment]
I'm having the same problem, and here's what I discovered.

1. While viewing the quest, down in the bottom-right of the viewport should be a pencil icon that will enable editing mode -- not sure if you need to be an admin on the server or if any player is allowed to do this.
2. In editing mode, right-click the Time for FREEDOM! quest
3. From the context menu that appears, click "Reset Progress"

![Screenshot of the context menu offering Reset Progress](https://github.com/user-attachments/assets/84f2c72a-2c4a-49d7-b7f5-ca1e8b7b1b2e)

There is another "Complete Instantly" option, but I found that by using this you do not get the rewards (they are marked as already received), and if the rest of the chapter is already complete before marking this last one as complete, the chapter will still show the "in progress" teal color rather than the "complete" green color.
