### ISSUE TITLE
Loading nether crashes the server

### ISSUE THREAD

**Issue by Ponnes000** [FTBTeam/FTB-Modpack-Issues#5724]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Every time we load the nether the server crashes. We have 12 GB memory and it crashes even if we are online 1 at a time. 

### Steps to reproduce

1. Enter nether portal.
2. Crash

### Expected behaviour

To load the nether

**Comment by Ponnes000** [comment]
We fixed it by turning it off and on again

**Comment by Dylansweaver** [comment]
I am now having this same issue, what did you turn off and on again to fix it? the Nether portal or the whole server? I've tried deleting the nether world file and everything, still get server crash when I try to enter

**Comment by Dylansweaver** [comment]
> I am now having this same issue, what did you turn off and on again to fix it? the Nether portal or the whole server? I've tried deleting the nether world file and everything, still get server crash when I try to enter

Found a fix for future people trying to solve, I went into a single player game, made a portal, went to the nether, then took the generated nether world files and used it for the server nether
