### ISSUE TITLE
Mine colonies - Rally banner not working

### ISSUE THREAD

**Issue by T-Blade** [FTBTeam/FTB-Modpack-Issues#5905]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When using the Rally banner, Calling the guards does not make them respond. I get system feedback the guards are called, but nothing happens.
Using the guard hut and setting the guards to follow me does work.

### Steps to reproduce

1) equip Rally banner
2) Shift right click a guard tower main block to add it to you list
3) Shift right click in the air / another block to summon the guards to you (normally)
4) Nothing happens

### Expected behaviour

The guards should come to me and follow

### Screenshots

![image](https://github.com/user-attachments/assets/a1b857cb-a3c7-4687-85a3-c37298fd6919)

### Additional information

Server is not modified, however the client version is, none of those normally should have any effect:
iris-neoforge-1.8.0-beta.4+mc1.21.1
DistantHorizons-2.2.1-a-1.21.1-neo-fabric
inventoryessentials-neoforge-1.21.1-21.1.1

**Comment by Saereth** [comment]
updated minecolonies should resolve this

**Comment by T-Blade** [comment]
Sadly this did not resolve the isseu.
I also ran a creative world with copied instance where i removed the 3 mods i added myself.

Sadly in both versions, the rally banner does not work.

**Comment by TheZDog** [comment]
This is till not fixed?

**Comment by T-Blade** [comment]
still not working for me at least. I tested it earlier today again, and rally banner is still useless.

**Comment by Glemoyn** [comment]
I can confirm that I am using this modpack and the rallying banner is not working for me.
