### ISSUE TITLE
*lots* of "No registration for payload oritech:particles; refusing to decode" log entries.

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-Modpack-Issues#7795]
### Modpack

FTB OceanBlock 2

### Modpack version

1.11.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

i have about 200 MB of the following in latest.log since i installed the 1.11 update. It was doing this in 1.10.1 as well but since this was mentioned in the 1.11 changelog i figured i'd file an issue that it seems to not be fixed.

```
[20May2025 07:37:56.033] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.033] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.033] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.033] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.034] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.034] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.034] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.034] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.034] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.084] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.085] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.134] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.134] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.183] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.183] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.183] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.183] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.184] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.234] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.234] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
[20May2025 07:37:56.283] [Netty Epoll Server IO #0/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: No registration for payload oritech:particles; refusing to decode.
```

### Describe the bug

Logs full of decode refusals for oritech:particles.

### Steps to reproduce

1. launch dedicated server
2. look at logs

### Expected behaviour

less logs about this error?

### Additional information

Upstream issues:

Oritech: https://github.com/Rearth/Oritech/issues/358

owo-lib: https://github.com/wisp-forest/owo-lib/issues/384

**Comment by natebc** [comment]
This is still present in 1.11.1 as well.

**Comment by ImortalFrog** [comment]
I was watching my console while playing earlier tonight on 1.11.1 

Noticed the spam had stopped for a moment after changing up some cables.  

Then I started working on my Solar Panels (making an island for them) and the error came back... 

Took down the newly built ones and rebuilt them, as I was rebuilding them my stack of cores ran out and when I cliked on the machine it gave the glowy brick outline and the error came right back 

Broke the bocks for the one I was buliding and the one next to it and it stopped.

Feels like the error comes from BUILDING an Oritech Multiblock and either clicking on it without enough cores and/or building it too close in proximity to another.   

Good luck! hope this helps!

**Comment by HumnResources** [comment]
Bump. Confirmed still an issue on my server. Makes using the logs for anything meaningful basically impossible lmao.

**Comment by natebc** [comment]
The upstream issue https://github.com/Rearth/Oritech/issues/358 has been fixed! So, assuming everything goes okay and they release an update, we should get *hopefully* get that update the next time the pack updates! 🤞🏼

**Comment by rhullah** [comment]
Was this missed in the latest update (1.12.2)? Oritech says it was fixed in 0.16 of it's version, but 1.12.2 was not updated to use that version.

**Comment by nemured** [comment]
> Was this missed in the latest update (1.12.2)? Oritech says it was fixed in 0.16 of it's version, but 1.12.2 was not updated to use that version.

it still happened in 1.12.2.But if you don't put the oritech block too close,that's fine

**Comment by Jamoky** [comment]
I get this once I have the steam engine getting steam and the animation starts.  How far away do you need to put it to not get the message? Guess its time to work on producing other power.

**Comment by nemured** [comment]
> I get this once I have the steam engine getting steam and the animation starts. How far away do you need to put it to not get the message? Guess its time to work on producing other power.

seem that 1 is ok,make sure they dont use the same block. By the way,the Obsidian productor machine also have problem,dont use it.

**Comment by nemured** [comment]
> I get this once I have the steam engine getting steam and the animation starts. How far away do you need to put it to not get the message? Guess its time to work on producing other power.

用热交换发电机代替蒸汽机，做个热交换发电机阵列（64个），就不愁吃喝了
using Thermoelectric Generator instead of steam

**Comment by rhullah** [comment]
Temporary Workaround: I hope it's ok that I share this but we really need to be able to read our servers console logs, so this is something you can do to remove the console spam until the modpack updates Oritech to a version that has this built in.

The way Oritech fixed this was to just [filter/suppress the log message](https://github.com/Rearth/Oritech/blob/9d6aedb4656303bd6f19f4332189acf4cd2fabe8/neoforge/src/main/java/rearth/oritech/neoforge/mixin/NetworkWarningShutupMixin.java). Because of that, we can do that with a mod that allows you to setup any filter to suppress any log message.  I've been using Log Filter, available on [Modrinth](https://modrinth.com/mod/log-filter) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/log-filter).  All you need to do is install the mod as normal (drop the mod into the mods folder) and then copy the following into a file at the location `config/log_filter.json`.  You will likely need to create this file as it won't exists unless you're already using this mod.

```json
{
  "logEvents": "NONE",
  "rules": [
    {
      "level": [
        {
          "relation": "EQUAL",
          "value": "WARN"
        }
      ],
      "loggerName": [
        {
          "relation": "MATCH",
          "value": "net.neoforged.neoforge.network.registration.NetworkRegistry"
        }
      ],
      "formatMessage": [
        {
          "relation": "MATCH",
          "value": "No registration for payload {}; refusing to decode."
        }
      ],
      "parameterClasses": [
        {
          "0": {
            "relation": "MATCH",
            "value": "net.minecraft.resources.ResourceLocation"
          }
        }
      ],
      "parameterValues": [
        {
          "0": {
            "relation": "MATCH",
            "value": "oritech:particles"
          }
        }
      ]
    }
  ]
}
```

**Comment by Jamoky** [comment]
Thanks.  Good to know that the fix was only to stop the spam from showing up.  Since I did not need a crazy amount of power, I ended up added to the Thermoelectric Generator I had, 4 windmills and a water wheel.

**Comment by natebc** [comment]
@ArtpokeBr, 
I'll take a look today. This issue actually caused me to stop playing the pack so if it's really fixed I'll be very happy to pick it back up.
