### ISSUE TITLE
Key Binds reset on launch

### ISSUE THREAD

**Issue by sitnoveter** [FTBTeam/FTB-Modpack-Issues#8583]
### Modpack

FTB Skies 2

### Modpack version

1.5.1

### Launcher

FTB App

### Describe the bug

All key binds reset when re-oppening the game.

### Steps to reproduce

Oppen game.
change a key bind.
close game.
Oppen game, key bind has been changed to default.

### Expected behaviour

Key Binds to stay as decided by player

### Has the pack been modified

Please select an option...

### Additional information

Did not try with all keybinds, but the ones I noticed were:
wireless crafting from AE, Ultimine, zoom, quets

**Comment by itskenny7** [comment]
This is fixed in 1.5.1 normally, I just updated the pack and everything is back to normal.

**Comment by Gaz492** [comment]
> ### Modpack
> 
> FTB Skies 2
> ### Modpack version
> 
> 1.5.1
> ### Launcher
> 
> FTB App
> ### Describe the bug
> 
> All key binds reset when re-oppening the game.
> ### Steps to reproduce
> 
> Oppen game. change a key bind. close game. Oppen game, key bind has been changed to default.
> ### Log Files
> 
> _No response_
> ### Expected behaviour
> 
> Key Binds to stay as decided by player
> ### Has the pack been modified
> 
> Please select an option...
> ### Additional information
> 
> Did not try with all keybinds, but the ones I noticed were: wireless crafting from AE, Ultimine, zoom, quets

Can you confirm that this is still an issue in 1.5.1 for you, as it should have been fixed

**Comment by sitnoveter** [comment]
It has been fixed for me on 1.5.1
