### ISSUE TITLE
Local Server Filewatcher issue

### ISSUE THREAD

**Issue by AlphaKintari** [FTBTeam/FTB-Modpack-Issues#9294]
### Modpack

FTB StoneBlock 4

### Modpack version

1.0

### Launcher

FTB App

### Describe the bug

After launching the server and the server loading, it keeps logging this warning about twice a second:

```
[07:46:36] [FileWatcher-1-thread-1/WARN] [ne.ne.fm.co.ConfigTracker/CONFIG]: Configuration file G:\Minecraft\_Servers\FTB StoneBlock 4\config\chicken_roost-server.toml is not correct. Correcting
[07:46:37] [FileWatcher-1-thread-1/WARN] [ne.ne.fm.co.ConfigTracker/CONFIG]: Configuration file G:\Minecraft\_Servers\FTB StoneBlock 4\config\chicken_roost-server.toml is not correct. Correcting
[07:46:37] [FileWatcher-1-thread-1/WARN] [ne.ne.fm.co.ConfigTracker/CONFIG]: Configuration file G:\Minecraft\_Servers\FTB StoneBlock 4\config\chicken_roost-server.toml is not correct. Correcting
[07:46:38] [FileWatcher-1-thread-1/WARN] [ne.ne.fm.co.ConfigTracker/CONFIG]: Configuration file G:\Minecraft\_Servers\FTB StoneBlock 4\config\chicken_roost-server.toml is not correct. Correcting
[07:46:38] [FileWatcher-1-thread-1/WARN] [ne.ne.fm.co.ConfigTracker/CONFIG]: Configuration file G:\Minecraft\_Servers\FTB StoneBlock 4\config\chicken_roost-server.toml is not correct. Correcting
```

<img width="1828" height="505" alt="Image" src="https://github.com/user-attachments/assets/80b435c8-e99d-4ef6-af92-f06e50d0d9af" />

Server still works, and players can login.

### Steps to reproduce

Configure and launch local server.  

### Expected behaviour

This warning should not keep spamming the log. :)

### Has the pack been modified

No

**Comment by AlphaKintari** [comment]
[debug.zip](https://github.com/user-attachments/files/23234532/debug.zip)
Sure can! 

The only config I modified was the FTBChunks to always allow chunkloading even if no one is online.

**Comment by natebc** [comment]
Interesting. i hit this on 1.0.2 on the first load but not the second.

**Comment by PatrickMcDonald** [comment]
I'm also getting this still, new install of 1.0.1, now upgraded to 1.0.3
On Mac (arm)

[debug.zip](https://github.com/user-attachments/files/23289848/debug.zip)

**Comment by TarantelTM** [comment]
should be fixed in latest version 1.0.3.
changed configsystem complete so first launch will correct my configs now and new installs should work fine now.

**Comment by PatrickMcDonald** [comment]
I've updated my server to the latest version (1.0.5) and I'm still getting spammed with configuration file /Users/***/minecraft/servers/StoneBlock4/config/chicken_roost-server.toml is not correct. Correcting

Is there a change I can make on the server configs to fix this, or do I need to go to a fresh install?

**Comment by PatrickMcDonald** [comment]
This is fixed now for me in 1.0.8, thank you
